[package]
name = "ferrum-calc"
description = "Formula parsing and evaluation for FerrumOffice."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ferrum-core.workspace = true

[lints]
workspace = true
